// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNS4FUkdOqlSq51upe_shLt04jHbQ3JIg',
    appId: '1:217816157716:web:1627970d2bdce98ed62101',
    messagingSenderId: '217816157716',
    projectId: 'login-firebase-df9b0',
    authDomain: 'login-firebase-df9b0.firebaseapp.com',
    storageBucket: 'login-firebase-df9b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNG3y0fGC_y9s3Bg-XhCmQgpDLJMT5smo',
    appId: '1:217816157716:android:93f531d34547438fd62101',
    messagingSenderId: '217816157716',
    projectId: 'login-firebase-df9b0',
    storageBucket: 'login-firebase-df9b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9iyyjWlk3dJWi4bhZ2pJJX7C0m3IZ7_4',
    appId: '1:217816157716:ios:373320584509d92bd62101',
    messagingSenderId: '217816157716',
    projectId: 'login-firebase-df9b0',
    storageBucket: 'login-firebase-df9b0.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9iyyjWlk3dJWi4bhZ2pJJX7C0m3IZ7_4',
    appId: '1:217816157716:ios:373320584509d92bd62101',
    messagingSenderId: '217816157716',
    projectId: 'login-firebase-df9b0',
    storageBucket: 'login-firebase-df9b0.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNS4FUkdOqlSq51upe_shLt04jHbQ3JIg',
    appId: '1:217816157716:web:27277b467e35543bd62101',
    messagingSenderId: '217816157716',
    projectId: 'login-firebase-df9b0',
    authDomain: 'login-firebase-df9b0.firebaseapp.com',
    storageBucket: 'login-firebase-df9b0.firebasestorage.app',
  );
}
